---
- hosts: all
  become: true
  tasks:

  - name: Install httpd webserver
    yum: name=httpd state=present

  - name: Runnning httpd
    service: name=httpd state=started      

  - name: Open port 80 http access
    firewalld:
      service: http
      permanent: true
      state: enabled

  - name: Restart Firewall service. For firewall changes
    service: name=firewalld state=restarted
